export enum CardType {
  Explain = "explain",
  ImageExplain = "image_explain",
  Quiz = "quiz",
  MultipleChoice = "multiple_choice",
  TrueFalse = "true_false",
  FillBlank = "fill_blank",
  Blurting = "blurting",
  Feynman = "feynman",
  Timeline = "timeline",
  Match = "match",
  Order = "order",
  ErrorDetection = "error_detection",
  MemoryRecall = "memory_recall",
  VisualRecall = "visual_recall",
  Audio = "audio",
  Future = "future",
}
