import type { ParsedKnowledgeJson } from "@/ai/schema";

export function makeKnowledgeJson(
  overrides: Partial<ParsedKnowledgeJson> = {}
): ParsedKnowledgeJson {
  return {
    metadata: {
      documentId: "doc-1",
      title: "Capitolo test",
      subject: "Matematica",
      language: "it",
      estimatedReadingTimeMinutes: 10,
      estimatedStudyTimeMinutes: 20,
      chapterNumber: 1,
      sourcePages: 3,
      generatedAt: "2026-07-31T10:00:00.000Z",
      version: "1.0.0",
    },
    atoms: [
      {
        id: "atom-a",
        title: "Atomo A",
        summary: "Riassunto A",
        explanation: "Spiegazione A",
        importance: 3,
        difficulty: 2,
        prerequisites: [],
        learningObjectives: ["understand"],
        keywords: ["a"],
        aliases: [],
        formulas: [],
        definitions: [],
        examples: [],
        counterExamples: [],
        commonMistakes: [],
        misconceptions: [],
        applications: [],
        historicalContext: null,
        notes: null,
        images: [],
        tables: [],
        diagrams: [],
        equations: [],
        citations: [],
        pageReferences: [1],
        confidence: 0.9,
      },
      {
        id: "atom-b",
        title: "Atomo B",
        summary: "Riassunto B",
        explanation: "Spiegazione B",
        importance: 4,
        difficulty: 3,
        prerequisites: ["atom-a"],
        learningObjectives: ["apply"],
        keywords: ["b"],
        aliases: [],
        formulas: [],
        definitions: [],
        examples: [],
        counterExamples: [],
        commonMistakes: [],
        misconceptions: [],
        applications: [],
        historicalContext: null,
        notes: null,
        images: [],
        tables: [],
        diagrams: [],
        equations: [],
        citations: [],
        pageReferences: [2],
        confidence: 0.85,
      },
    ],
    ...overrides,
  };
}
